repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: check-symlinks
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=1024']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
    args:
      - "--check-untyped-defs"
    additional_dependencies:
      - "django-stubs==1.13.1"
      - "types-setuptools==65.7.0.2"
      - "types-requests==2.28.11.8"
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    stages: ["commit"]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
